/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app;

import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Zelbag
 */
public class FrmMenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public FrmMenuPrincipal() {
        initComponents();
        load();
    }

    private void load(){
        FrmListaPerros ventanaPerros;
        try {
            ventanaPerros = new FrmListaPerros(this);
            DpnlEscritorio.add(ventanaPerros);
            ventanaPerros.show();
        } catch (PropertyVetoException ex) {
            Logger.getLogger(FrmMenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DpnlEscritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mitmListaPerros = new javax.swing.JMenuItem();
        mitmListaBaja = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        mitmListaDuenios = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mitmListaEnfermedades = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mitmListaRazas = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        mitmListaEstados = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout DpnlEscritorioLayout = new javax.swing.GroupLayout(DpnlEscritorio);
        DpnlEscritorio.setLayout(DpnlEscritorioLayout);
        DpnlEscritorioLayout.setHorizontalGroup(
            DpnlEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1038, Short.MAX_VALUE)
        );
        DpnlEscritorioLayout.setVerticalGroup(
            DpnlEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 765, Short.MAX_VALUE)
        );

        jMenu1.setText("Perro");

        mitmListaPerros.setText("Listado en refugio");
        mitmListaPerros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitmListaPerrosActionPerformed(evt);
            }
        });
        jMenu1.add(mitmListaPerros);

        mitmListaBaja.setText("Listado de bajas");
        mitmListaBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitmListaBajaActionPerformed(evt);
            }
        });
        jMenu1.add(mitmListaBaja);

        jMenuBar1.add(jMenu1);

        jMenu4.setText("Dueño");

        mitmListaDuenios.setText("Listado de dueños");
        jMenu4.add(mitmListaDuenios);

        jMenuBar1.add(jMenu4);

        jMenu3.setText("Enfermedad");

        mitmListaEnfermedades.setText("Listado de enfermedades");
        jMenu3.add(mitmListaEnfermedades);

        jMenuBar1.add(jMenu3);

        jMenu2.setText("Raza");

        mitmListaRazas.setText("Listado de razas");
        mitmListaRazas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitmListaRazasActionPerformed(evt);
            }
        });
        jMenu2.add(mitmListaRazas);

        jMenuBar1.add(jMenu2);

        jMenu5.setText("Estado");

        mitmListaEstados.setText("Listado de estados");
        mitmListaEstados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitmListaEstadosActionPerformed(evt);
            }
        });
        jMenu5.add(mitmListaEstados);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DpnlEscritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DpnlEscritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mitmListaPerrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitmListaPerrosActionPerformed
        // TODO add your handling code here:
        FrmListaPerros ventanaPerros;
        try {
            ventanaPerros = new FrmListaPerros(this);
            var jFrame = DpnlEscritorio.getSelectedFrame();
            if(jFrame != null){
                jFrame.dispose();
                DpnlEscritorio.removeAll();            
            }
            DpnlEscritorio.add(ventanaPerros);
            ventanaPerros.show();
        } catch (PropertyVetoException ex) {
            Logger.getLogger(FrmMenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_mitmListaPerrosActionPerformed

    private void mitmListaBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitmListaBajaActionPerformed
        // TODO add your handling code here:
        FrmListaPerros ventanaPerros;
        try {
            ventanaPerros = new FrmListaPerros(this);
            DpnlEscritorio.removeAll();
//            DpnlEscritorio.add(ventanaPerros);
//            ventanaPerros.show();
        } catch (PropertyVetoException ex) {
            Logger.getLogger(FrmMenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mitmListaBajaActionPerformed

    private void mitmListaRazasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitmListaRazasActionPerformed
        // TODO add your handling code here:
        FrmListaRazas ventanaRazas;
        try {
            ventanaRazas = new FrmListaRazas(this);
            var jFrame = DpnlEscritorio.getSelectedFrame();
            if(jFrame != null){
                jFrame.dispose();
                DpnlEscritorio.removeAll();            
            }
            DpnlEscritorio.add(ventanaRazas);
            ventanaRazas.show();
        } catch (PropertyVetoException ex) {
            Logger.getLogger(FrmMenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mitmListaRazasActionPerformed

    private void mitmListaEstadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitmListaEstadosActionPerformed
        // TODO add your handling code here:
        FrmListaEstados ventanaEstados;
        try {
            ventanaEstados = new FrmListaEstados(this);
            var jFrame = DpnlEscritorio.getSelectedFrame();
            if(jFrame != null){
                jFrame.dispose();
                DpnlEscritorio.removeAll();            
            }DpnlEscritorio.add(ventanaEstados);
            ventanaEstados.show();
        } catch (PropertyVetoException ex) {
            Logger.getLogger(FrmMenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
               
    }//GEN-LAST:event_mitmListaEstadosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane DpnlEscritorio;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mitmListaBaja;
    private javax.swing.JMenuItem mitmListaDuenios;
    private javax.swing.JMenuItem mitmListaEnfermedades;
    private javax.swing.JMenuItem mitmListaEstados;
    private javax.swing.JMenuItem mitmListaPerros;
    private javax.swing.JMenuItem mitmListaRazas;
    // End of variables declaration//GEN-END:variables
}
