package app;

/**
 *
 * @author Esteban
 */
public class Menu extends javax.swing.JFrame {

    public static AltaResidente Ap;
    public static BajaPerros Bp;
    //public static ListarPerros Lp;

    public static AltaResidente getAp() {
        return Ap;
    }

    public static void setAp(AltaResidente Ap) {
        Menu.Ap = Ap;
    }

    public static BajaPerros getBp() {
        return Bp;
    }

    public static void setBp(BajaPerros Bp) {
        Menu.Bp = Bp;
    }

    /*public static ListarPerros getLp() {
        return Lp;
    }

    public static void setLp(ListarPerros Lp) {
        Menu.Lp = Lp;
    }*/


    
    
    public Menu(){
        initComponents();
        look();
    }
            
            
    /*public Menu(AltaPerros ap, BajaPerros bp, ListarPerros lp) {
        initComponents();
        Menu.setAp(ap);
        Menu.setBp(bp);
        Menu.setLp(lp);//deberian ser Menu.getLp(lp); pero si lo pongo da error
        look();
    }*/

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        altaPerros = new javax.swing.JButton();
        listaPerros = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Refugio Candelaria");
        jLabel1.setBorder(new javax.swing.border.MatteBorder(null));

        altaPerros.setText("Alta de Perros");
        altaPerros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                altaPerrosActionPerformed(evt);
            }
        });

        listaPerros.setText("Listado de Perros");
        listaPerros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaPerrosActionPerformed(evt);
            }
        });

        jButton4.setText("Salir");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(altaPerros, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                            .addComponent(listaPerros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(119, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(39, 39, 39))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(altaPerros)
                .addGap(31, 31, 31)
                .addComponent(listaPerros)
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listaPerrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaPerrosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listaPerrosActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void altaPerrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_altaPerrosActionPerformed
       //Menu.getAp().setVisible(true);
       //new AltaResidente().show(); iba esta antes y funcionaba normal                                         
        MenuAlta ventanaMenuAlta = new MenuAlta(this, true);
       ventanaMenuAlta.show();
        
    }//GEN-LAST:event_altaPerrosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void look(){
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton altaPerros;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton listaPerros;
    // End of variables declaration//GEN-END:variables
}
